### ISSUE TITLE
向大佬提个需求：能不能加个正向代理

### ISSUE THREAD

**Issue by liangnicho** [1again/SmartProxyPool#11]
需求：
启动一个 HTTP 正向代理服务器（Forward Proxy Server）。 这个服务器会从数据库中选择一个刚更新过的代理，并将其用作正向代理。 每当发出 HTTP 请求时，代理服务器将随机选择一个代理。

**Comment by joson1205** [comment]
没有设计删除机制吗?

**Comment by 1again** [comment]
你这个需求貌似已经做了吧.
你看看文档是你要的吗.
这个叫动态代理.

**Comment by liangnicho** [comment]
是我傻逼了，没看到。
